name: BuildTest
on:
  push:
    branches:
       - main
       - manifoldSplitter
  pull_request:
    branches:
       - main
       - manifoldSplitter

jobs:
  docker-build-test-ubuntu:
    runs-on: ubuntu-latest
    name: BuildTestUbuntu
    steps:
      # First check out the repository to get the docker file
      - name: Checkout
        uses: actions/checkout@v2
      # Now build in a container with all deps
      - name:  DockerBuildTestPush
        run: docker build -t ci-libskin-ubuntu docker/skinning-ubuntu/